### ISSUE TITLE
Installing a module that relies on CacheItemPoolInterface

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1816]
## Type
- Non critical bug
## Problem description

> When installing Fork CMS, it seems that you can't install a custom module that relies on "cache.pool"? The strange thing is dat the Pages module has the same but doesn't throw an error?

```
Catchable Fatal Error: Argument 2 passed to Backend\Modules\MediaLibrary\Engine\CacheBuilder::__construct() must be an instance of Psr\Cache\CacheItemPoolInterface, instance of stdClass given, called in /Sites/fork-cms-4-3/app/cache/install/appInstallDebugProjectContainer.php on line 1841 and defined
```

<img width="622" alt="schermafbeelding 2016-10-28 om 16 53 30" src="https://cloud.githubusercontent.com/assets/588616/19810789/17f7e98e-9d2f-11e6-9814-6a7e02cc1b37.png">

```
services:
    media_library.cache_builder:
        class: Backend\Modules\MediaLibrary\Engine\CacheBuilder
        arguments:
            - "@database"
            - "@cache.pool"
            - "@media_library.repository.group"
```
## Steps to reproduce

> Describe how we can reproduce the problem here
## Expected behavior / Proposed solutions

> explain what you had expected to happen and or a solution
