### ISSUE TITLE
Non-existent parameter "templating.engines"

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#834]
I just cloned Fork 3.8 and I was about to install it. First I ran `composer install`. It returned an error at the end:

```
Script app/console assets:install . && cd tools && ./remove_cache handling the post-install-cmd event returned with an error

[RuntimeException]                                                                
Error Output:                                                                                                                           
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]    
You have requested a non-existent parameter "templating.engines".
```

However, in config.yml I see templating.engines so what's the problem?

```
framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
```

Any idea? Probably a sloppy error somewhere.
